apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    email: mark.cornick@cava.com
    http01: {}
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v01.api.letsencrypt.org/directory
