apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: chat-cavagrill-org
  namespace: default
spec:
  acme:
    config:
    - domains:
      - chat.cavagrill.org
      http01:
        ingress: chat
  commonName: chat.cavagrill.org
  issuerRef:
    name: letsencrypt
  secretName: chat-cavagrill-org-tls
